apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app1
spec:
  strategy: 
    type: Recreate
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app1
          image: devopstrainingschool/knote-jenkins:71
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL1
              value: mongodb://my-db-service1:27017/dev
          imagePullPolicy: Always
